# polymorphism in python there will be a three types of polymorphism 
# 1. duCK TYPE POLYMORPHISM
# 2. OVERLOADING WILL BE A THREE TYPES 
#   1. OPERATOR OVERLOADING
#   2. METHOD OVERLOADING
#   3. CONSTRUCTOR OVERLOADING
# 3. OVERRIDING WILL BE A TWO TYPES OF OVERIDING
#   1. METHOD OVERRIDING
#   2. CONSTRUCTOR OVERRIDING
