# polymorphism in python there will be a three types of polymorphism 
# 1. duCK TYPE POLYMORPHISM
# 2. OVERLOADING WILL BE A THREE TYPES 
#   1. OPERATOR OVERLOADING
#   2. METHOD OVERLOADING
#   3. CONSTRUCTOR OVERLOADING
# 3. OVERRIDING WILL BE A TWO TYPES OF OVERIDING
#   1. METHOD OVERRIDING
#   2. CONSTRUCTOR OVERRIDING


# METHOD OVERLOADING - WHEN WE DECLARE A FUNCTION WHICH HAVING SAME NAME BUT PASSING PARAMETER IS DIFFERENT THEN SUCH TYPE OF FUNCTION DECLEARATION IS KNOWN ASS METHOD OVERLOADING  OR FUNCTION OVERLOADING
# BECAUSE OF PYTHON IS A DYNAMICALLY TYPED WE CAN NOT ACHIEVED FUNCTION OVERLOADING

def func1(a):
    print("Value is a= ",a)
def func2(b,c):
    print("Value is =",b)
func1(4,8)        
